name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
     branch_name:
        description: 'Branch name'
        required: true
        type: choice
        options:
        - main
        - qa
        - dev
jobs:
  envbranch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['${{ github.event.inputs.branch_name }}']  # Note the quotes around the expression
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check the branch and select the environment
        id: branch_check
        run: |
          echo "Running on branch ${{ github.event.inputs.branch_name }}"
          if [ "${{ github.event.inputs.branch_name }}" = "main" ]; then  
            echo "env_name=Prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.branch_name }}" = "qa" ]; then    
            echo "env_name=QA" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.branch_name }}" = "dev" ]; then    
            echo "env_name=dev" >> $GITHUB_OUTPUT            
          fi
      - name: I am in main
        run: echo "I am in main"
  create-tag:
    runs-on: ubuntu-latest
    needs: 
      - envbranch    
    environment:
      name: Prod
    env:
      GIT_TOKEN: "${{ secrets.GIT_TOKEN }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git branch
          git config --global user.email "sankumar.549@gmail.com"
          git config --global user.name "sankumar11"
          git config --global credential.helper store 
      - name: Create tag
        run: |
          git tag -a v2.0 -m "Version v2.0"
          git tag
          git push origin v2.0 --follow-tags --force
        
#      - name: Push tag to repository
#        run: git push origin v2.0
