name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
     branch_name:
        description: 'Branch name'
        required: true

jobs:
  envbranch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['${{ github.event.inputs.branch_name }}']  # Note the quotes around the expression
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check the branch and select the environment
        id: branch_check
        run: |
          case "${{ github.event.inputs.branch_name }}" in
          hotfix-*) echo "env_name=UAT" >> $GITHUB_OUTPUT ;;
          qa) echo "env_name=QA" >> $GITHUB_OUTPUT ;;
          esac
#      - name: I am in "${{ steps.branch_check.outputs.env_name }}"
      - name: Use variable setup in previous step
        run: echo "Using envirnoment ${{ steps.branch_check.outputs.env_name }}"      
        #run: echo "I am in main"
  create-tag:
    runs-on: ubuntu-latest
    needs: 
      - envbranch    
#    environment:
#      name: Prod
#    env:
#      GITHUB_TOKEN: "${{ secrets.GIT_TOKEN }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git branch
          git config --global user.email "sankumar.549@gmail.com"
          git config --global user.name "sankumar11"
      - name: Generate random tag name
        id: random_tag
        run: echo "::set-output name=tag::v$(date +'-%Y%m%d-%H%M%S')"
        #echo "::set-output name=tag::v$(date +'%Y%m%d-%H%M%S')"
        #echo "::set-output name=tag::v$(date +'-%Y%m%d%H%M%S')"
      
      - name: Create tag
        run: |
          git tag -a ${{ steps.random_tag.outputs.tag }} -m "Version ${{ steps.random_tag.outputs.tag }}"
          git tag
      
      - name: Push tag to repository
        run: git push origin ${{ steps.random_tag.outputs.tag }}

          
#      - name: Create tag
#        run: |
#          git tag -a v4.0 -m "Version v4.0"
#          git tag
        
#      - name: Push tag to repository
#        run: git push origin v4.0
